apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /food
            pathType: Prefix
            backend:
              service:
                name: food-service
                port:
                  number: 80
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: cook-service
                port:
                  number: 80
          # - path: /notification
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: notification-service
          #       port:
          #         number: 8080
