apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15  # Replace with your preferred PostgreSQL version
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "user"          # Updated username
        - name: POSTGRES_PASSWORD
          value: "pass"          # Updated password
        - name: POSTGRES_DB
          value: "cook_service"  # Updated database name
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"  # Use a subdirectory
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - name: postgres-port
    port: 5432
    targetPort: 5432
  selector:
    app: postgres